// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdkqtgullbuashhyebvr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFka3F0Z3VsbGJ1YXNoaHllYnZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MTc5MDAsImV4cCI6MjA1ODM5MzkwMH0.wfdZhwkH-LRCZVeBc4i5xw6JNyoXlTHnbnw1WiTli4g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);